{
 "title": "SRE Command Center",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "🚨 TOTAL ALERTS RECEIVED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(alerts_received_total)" }
   ]
  },
  {
   "title": "📈 ALERT RATE (Per Severity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(alerts_received_total[1m])",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "⏱️ MTTA (Temps Moyen Prise en Compte)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(incident_mtta_seconds_sum[5m]) / rate(incident_mtta_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "🛠️ MTTR (Temps Moyen Résolution)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(incident_mttr_seconds_sum[5m]) / rate(incident_mttr_seconds_count[5m])"
    }
   ]
  }
 ]
}